language: node_js
node_js: '7'
script:
- npm run test:ci
addons:
  sauce_connect:
    username: xerona
    access_key:
      secure: KMUbRyMNWC5fzatmLxNIDF1VeCL4uVczr+Po2jdvXIlHk4o/WTzxo89bDiPbUcecmD2fyuM/hJ9VG8kLXac9okiUOFGYPgJowJ/dcQKhXhx0Q8tg+MmoiWkIUJaU4gKRaQnUFYH3VTLSW4SOjYpveFm70370fu21V7fmdLTKwsG0y/5sq0n+RomWWm4vrluv0ymj8mTvVk4Ec6wxolzbsHpu9PtubvA2lLs0z4bs0OtpJ+OTeRxeyPfe9tX09nuTTmA1qgaWrqd/r8mMWMtyv12IDYWEjtO5gOoijs4bp4g6jJHxUwCuWH1SyJ1KfyouHhLceT3Mp6I5OomwDW1Ky9PGcoqHotKtT8tgL+vMdjpo/APEWZHFOtTEcvtR9CyIXH5oLvVR6priJFP6jGMaBJST8xTQu0xkyon3QvwkLKetkrz/lUctT2L4segjM0sEdz8QMWveNyP4nEH/1HdDfKy6qcuGM6mew9sH4YBm8sxCJnnwiJKYAjW2oTuoSfeBxzKqFonjJJ6Zmv6T9/Cp96dVsU6OEumQZdRxI1BeYr49yI4tBoom+ZNchVTkcHDkNG056hhPqsj3d38trVOjRUD9DuGdGplGjeR+MpHJ5swaAjv9+B8PAN4IBfr1I4zpxjRvkM6n7a6QQ22L6wBZe1LDigRmzRzQLvixYXqEbpY=
